server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: "1"
    basic_auth:
      username: promtail
      password: promtail
    batchwait: 1s
    batchsize: 102400
    timeout: 10s

scrape_configs:
  - job_name: app
    static_configs:
      - targets:
          - localhost
        labels:
          job: movie-api
          __path__: /var/log/app/*.log